{"uid":"63ff07f181fc742f","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1706768572335,"stop":1706768572447,"duration":112},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./cypress/support/e2e.js (webpack:///./cypress/support/e2e.js:20:10)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at 0 (http://localhost:40335/__cypress/tests?p=cypress/support/e2e.js:13777:18)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at eval (webpack:///webpack/bootstrap:83:0)\n    at eval (http://localhost:40335/__cypress/tests?p=cypress/support/e2e.js:87:10)\n    at eval (<anonymous>)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./cypress/support/e2e.js (webpack:///./cypress/support/e2e.js:20:10)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at 0 (http://localhost:40335/__cypress/tests?p=cypress/support/e2e.js:13777:18)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at eval (webpack:///webpack/bootstrap:83:0)\n    at eval (http://localhost:40335/__cypress/tests?p=cypress/support/e2e.js:87:10)\n    at eval (<anonymous>)","steps":[],"attachments":[{"uid":"ab126e946017024d","name":"cypress/e2e/spec5.cy.js:2024-02-01T06:22:52.368Z","source":"ab126e946017024d.png","type":"image/png","size":38245},{"uid":"9b05194a8c5fb514","name":"video recording","source":"9b05194a8c5fb514.mp4","type":"video/mp4","size":43845}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"package","value":"cypress.e2e.spec5.cy.js"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"63ff07f181fc742f.json","parameterValues":[]}