{"uid":"a16d7900a1ded7ba","name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","historyId":"c59643030e1e776644fd5d1d6aa79cfc","time":{"start":1706770229606,"stop":1706770229809,"duration":203},"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./cypress/support/e2e.js (webpack:///./cypress/support/e2e.js:20:10)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at 0 (http://localhost:43053/__cypress/tests?p=cypress/support/e2e.js:13777:18)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at eval (webpack:///webpack/bootstrap:83:0)\n    at eval (http://localhost:43053/__cypress/tests?p=cypress/support/e2e.js:87:10)\n    at eval (<anonymous>)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":4,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","statusTrace":"TypeError: The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./cypress/support/e2e.js (webpack:///./cypress/support/e2e.js:20:10)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at 0 (http://localhost:43053/__cypress/tests?p=cypress/support/e2e.js:13777:18)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at eval (webpack:///webpack/bootstrap:83:0)\n    at eval (http://localhost:43053/__cypress/tests?p=cypress/support/e2e.js:87:10)\n    at eval (<anonymous>)","steps":[],"attachments":[{"uid":"365f5a15a5c2f7a4","name":"cypress/e2e/spec3.cy.js:2024-02-01T06:50:29.648Z","source":"365f5a15a5c2f7a4.png","type":"image/png","size":38250},{"uid":"a7ae8962fb3032a","name":"video recording","source":"a7ae8962fb3032a.mp4","type":"video/mp4","size":64631}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"package","value":"cypress.e2e.spec3.cy.js"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"8ef71c1ba7c1df47","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1706770227378,"stop":1706770227480,"duration":102}},{"uid":"c14872d8afb907e9","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1706770227100,"stop":1706770227215,"duration":115}},{"uid":"589df529a86a1d91","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1706770224603,"stop":1706770224795,"duration":192}},{"uid":"387c4ef6521b788f","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1706770224238,"stop":1706770224429,"duration":191}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"892c823186ef585","reportUrl":"https://praveenjp12.github.io/cypress-project/23//#testresult/892c823186ef585","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > cy.allure.writeEnvironmentInfo is not a function\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","time":{"start":1706768574351,"stop":1706768574482,"duration":131}}]},"tags":[]},"source":"a16d7900a1ded7ba.json","parameterValues":[]}